In [3]:
import json
from pathlib import Path

import pandas as pd
from IPython.display import HTML, display

ROOT = Path.cwd().parent
JSON_DIR = ROOT / "JSON_Edit"

json_paths = sorted(JSON_DIR.glob("*.json"))
json_files = [p.name for p in json_paths]

print(f"JSON folder: {JSON_DIR}")
print(f"Total JSON files found: {len(json_files)}")

if not json_files:
    raise FileNotFoundError(f"No JSON files found in {JSON_DIR}")

# Show clickable file links in the notebook.
links_html = "<br>".join(
    f"<a href='file:///{path.as_posix()}' target='_blank'>{path.name}</a>"
    for path in json_paths
)
display(HTML(f"<b>Detected JSON files (JSON_Edit):</b><br>{links_html}"))

print("\n" + "=" * 80)
print("CATEGORY SUMMARY BY JSON FILE")
print("=" * 80)

file_category_counts = {}
file_category_item_counts = {}
summary_rows = []

for path in json_paths:
    print(f"\nJSON File: {path.name}")

    with open(path, "r", encoding="utf-8") as f:
        items = json.load(f)

    categories = []
    for item in items:
        for prop in item.get("Properties", []):
            category = str(prop.get("category", "")).strip()
            if category:
                categories.append(category)

    if categories:
        counts = pd.Series(categories, name="Category").value_counts(dropna=False)
        file_category_counts[path.name] = counts

        per_file_df = (
            counts.rename_axis("Category")
            .reset_index(name="Count")
            .sort_values(["Category"], kind="stable")
            .reset_index(drop=True)
        )

        file_category_item_counts[path.name] = int(per_file_df["Count"].sum())

        summary_rows.append(
            {
                "JSON File": path.name,
                "Distinct Categories": int(per_file_df["Category"].nunique()),
                "Total Category Entries": int(per_file_df["Count"].sum()),
            }
        )
    else:
        per_file_df = pd.DataFrame([
            {"Category": "<no categories found>", "Count": 0}
        ])
        file_category_counts[path.name] = pd.Series(dtype="int64")
        file_category_item_counts[path.name] = 0

        summary_rows.append(
            {
                "JSON File": path.name,
                "Distinct Categories": 0,
                "Total Category Entries": 0,
            }
        )

    display(per_file_df)

print("\n" + "=" * 80)
print("JSON-LEVEL SUMMARY TABLE")
print("=" * 80)
json_summary_df = pd.DataFrame(summary_rows).sort_values(["JSON File"]).reset_index(drop=True)
display(json_summary_df)

print("\n" + "=" * 80)
print("ALL CATEGORIES ACROSS ALL JSON FILES")
print("=" * 80)

all_categories = sorted(
    {
        category
        for counts in file_category_counts.values()
        for category in counts.index.tolist()
    }
)

# Matrix table: category x file (counts)
matrix_rows = []
for category in all_categories:
    row = {"Category": category}
    for file_name in json_files:
        counts = file_category_counts.get(file_name, pd.Series(dtype="int64"))
        value = counts.get(category)
        row[file_name] = int(value) if pd.notna(value) else 0
    matrix_rows.append(row)

category_matrix_df = pd.DataFrame(matrix_rows)
with pd.option_context("display.max_rows", len(category_matrix_df), "display.max_columns", None):
    display(category_matrix_df)

# General roll-up table for quick planning.
overall_rows = []
for category in all_categories:
    present_files = 0
    total_count = 0
    for file_name in json_files:
        counts = file_category_counts.get(file_name, pd.Series(dtype="int64"))
        value = counts.get(category)
        if pd.notna(value):
            present_files += 1
            total_count += int(value)

    overall_rows.append(
        {
            "Category": category,
            "Files Present": present_files,
            "Total Entries": total_count,
        }
    )

overall_category_df = (
    pd.DataFrame(overall_rows)
    .sort_values(["Files Present", "Total Entries", "Category"], ascending=[False, False, True], kind="stable")
    .reset_index(drop=True)
)

print("\nOverall category roll-up:")
with pd.option_context("display.max_rows", len(overall_category_df), "display.max_columns", None):
    display(overall_category_df)

print(f"\nTotal unique categories across JSON_Edit: {len(all_categories)}")

JSON folder: c:\Git\APS-IFC\JSON_Edit
Total JSON files found: 7

================================================================================
CATEGORY SUMMARY BY JSON FILE
================================================================================

JSON File: ACD-18040-ALL-ST-N2x3.json

                       Category  Count
0            Adaptive Component     16
1              Analysis Results     74
2         Analytical Properties   7881
3       Calculation Rules(Type)    364
4                   Constraints  66793
..                          ...    ...
61  Structural Section Geometry   3528
62               Supports(Type)    649
63                         Text      6
64               Top Rail(Type)   1395
65                       Treads   4321

[66 rows x 2 columns]

JSON File: ASTIDC-STAN-HE-EPD-MVB1-M-E-0002.json

                                 Category  Count
0                          ABB4HVDCDesign    168
1                  ABB4HVDCDesignRevision    300
2                ABB4ModelRevision Master     52
3                                 DB Part     52
4                                 DXF_DWG      4
5                                     IFC    192
6                          IFCAPPLICATION      3
7                         IFCORGANIZATION      1
8                         IFCOWNERHISTORY      3
9                               IFCPERSON      3
10               Instance Part Properties    961
11                                   Item   1279
12  Mass Properties Configuration Context     78
13                              Materials    332
14                empty property set name    110
15                            owning_user     56

JSON File: ASTIDC-STAN-HE-MPD-RHP1-M-M-0001.json

                                 Category   Count
0                          ABB4HVDCDesign   40252
1                  ABB4HVDCDesignRevision   53818
2                ABB4ModelRevision Master    3504
3                   DB Component Instance     422
4                                 DB Part    3272
5                                     IFC   44998
6                          IFCAPPLICATION       3
7                         IFCORGANIZATION       1
8                         IFCOWNERHISTORY       3
9                               IFCPERSON       3
10               Instance Part Properties  189478
11                                   Item  116307
12  Mass Properties Configuration Context   18638
13                              Materials   56140
14              Rolled-Up Mass Properties    3416
15                empty property set name   24036
16                            owning_user   13596

JSON File: ASTIDC-STAN-HE-MPD-TXBP1-M-M-0001.json

                                 Category  Count
0                          ABB4HVDCDesign   8404
1                  ABB4HVDCDesignRevision  17456
2                ABB4ModelRevision Master   1512
3                   DB Component Instance   1028
4                                 DB Part   3072
5                                     IFC  10463
6                          IFCAPPLICATION      3
7                         IFCORGANIZATION      1
8                         IFCOWNERHISTORY      3
9                               IFCPERSON      3
10               Instance Part Properties  48568
11                                   Item  46989
12  Mass Properties Configuration Context   2024
13                              Materials  12970
14              Rolled-Up Mass Properties   2592
15                 Routing System Defined      4
16                empty property set name   6786
17                            owning_user   3132

JSON File: Ifc2x3_Duplex_Architecture.json

                                  Category  Count
0                                      IFC   2198
1                           IFCAPPLICATION      3
2                  IFCDOORLININGPROPERTIES     56
3                             IFCDOORSTYLE    196
4                         IFCFURNITURETYPE    610
5                         IFCMATERIALLAYER     91
6                 IFCMATERIALLAYERSETUSAGE    543
7                          IFCORGANIZATION      1
8                          IFCOWNERHISTORY      2
9                                IFCPERSON      1
10               IFCWINDOWLININGPROPERTIES     96
11                          IFCWINDOWSTYLE    336
12                                    Item  11637
13             PSet_Revit_Analytical Model    156
14                  PSet_Revit_Constraints   2835
15                 PSet_Revit_Construction     68
16                   PSet_Revit_Dimensions    991
17                     PSet_Revit_Graphics     16
18                PSet_Revit_Identity Data    204
19       PSet_Revit_Materials and Finishes     32
20                        PSet_Revit_Other   3208
21                      PSet_Revit_Phasing    860
22                   PSet_Revit_Structural    470
23          PSet_Revit_Structural Analysis    364
24             PSet_Revit_Type_Constraints      8
25            PSet_Revit_Type_Construction   1244
26              PSet_Revit_Type_Dimensions   1230
27                PSet_Revit_Type_Graphics    412
28           PSet_Revit_Type_Identity Data   1354
29  PSet_Revit_Type_Materials and Finishes    726
30                   PSet_Revit_Type_Other  11857
31                  PSet_Revit_Type_Risers     14
32               PSet_Revit_Type_Stringers     20
33              PSet_Revit_Type_Structural     76
34                  PSet_Revit_Type_Treads     12
35                         Pset_BeamCommon     96
36                     Pset_BuildingCommon      2
37                     Pset_CoveringCommon     78
38                         Pset_DoorCommon    112
39                      Pset_RailingCommon     32
40                         Pset_RoofCommon      5
41                         Pset_SlabCommon    160
42                        Pset_SpaceCommon     44
43                        Pset_StairCommon     14
44                  Pset_StairFlightCommon     44
45                         Pset_WallCommon    570
46                       Pset_WindowCommon    192
47                              Quantities     44

JSON File: Ifc4_SampleHouse.json

                                   Category  Count
0                     Analytical Properties     72
1   Classification:Uniformat Classification     56
2                               Constraints    556
3                              Construction    192
4                                Dimensions    518
5                           Energy Analysis     40
6                                  Graphics     42
7                           Horizontal Grid     10
8                                       IFC    646
9                            IFCAPPLICATION      3
10                         IFCMATERIALLAYER      7
11                 IFCMATERIALLAYERSETUSAGE     42
12                          IFCORGANIZATION      1
13                          IFCOWNERHISTORY      2
14                                IFCPERSON      1
15                            Identity Data    200
16                                     Item   1938
17                   Materials and Finishes     88
18                                    Other    864
19                                  Phasing    236
20                      Pset_BuildingCommon      3
21                Pset_BuildingStoreyCommon      4
22                      Pset_CoveringCommon     24
23                   Pset_CurtainWallCommon      6
24                          Pset_DoorCommon     22
25         Pset_ManufacturerTypeInformation     28
26                        Pset_MemberCommon    200
27                         Pset_PlateCommon     60
28                          Pset_RoofCommon     12
29                          Pset_SlabCommon     24
30                         Pset_SpaceCommon      6
31                          Pset_WallCommon     48
32                        Pset_WindowCommon     32
33                               Quantities    158
34                               Structural     52
35                            Vertical Grid     10

JSON File: Snowdon+Towers+Sample+Structural2x3.json

                             Category  Count
0               Analytical Properties   1038
1   Classification:Uniformat:A1010100   1078
2   Classification:Uniformat:A1010110    126
3        Classification:Uniformat:B10   7196
4      Classification:Uniformat:B1010    308
..                                ...    ...
58                    Slab Shape Edit      4
59                         Structural  12390
60                Structural Analysis  12090
61        Structural Section Geometry   7576
62                   Structural(Type)     36

[63 rows x 2 columns]

================================================================================
JSON-LEVEL SUMMARY TABLE
================================================================================

,JSON File,Distinct Categories,Total Category Entries
0,ACD-18040-ALL-ST-N2x3.json,66,819830
1,ASTIDC-STAN-HE-EPD-MVB1-M-E-0002.json,16,3594
2,ASTIDC-STAN-HE-MPD-RHP1-M-M-0001.json,17,567887
3,ASTIDC-STAN-HE-MPD-TXBP1-M-M-0001.json,18,165010
4,Ifc2x3_Duplex_Architecture.json,48,43320
5,Ifc4_SampleHouse.json,36,6203
6,Snowdon+Towers+Sample+Structural2x3.json,63,294048

================================================================================
ALL CATEGORIES ACROSS ALL JSON FILES
================================================================================

,Category,ACD-18040-ALL-ST-N2x3.json,ASTIDC-STAN-HE-EPD-MVB1-M-E-0002.json,ASTIDC-STAN-HE-MPD-RHP1-M-M-0001.json,ASTIDC-STAN-HE-MPD-TXBP1-M-M-0001.json,Ifc2x3_Duplex_Architecture.json,Ifc4_SampleHouse.json,Snowdon+Towers+Sample+Structural2x3.json
0,ABB4HVDCDesign,0,168,40252,8404,0,0,0
1,ABB4HVDCDesignRevision,0,300,53818,17456,0,0,0
2,ABB4ModelRevision Master,0,52,3504,1512,0,0,0
3,Adaptive Component,16,0,0,0,0,0,0
4,Analysis Results,74,0,0,0,0,0,0
5,Analytical Properties,7881,0,0,0,0,72,1038
6,Calculation Rules(Type),364,0,0,0,0,0,0
7,Classification:Uniformat Classification,0,0,0,0,0,56,0
8,Classification:Uniformat:A1010100,0,0,0,0,0,0,1078
9,Classification:Uniformat:A1010110,0,0,0,0,0,0,126
10,Classification:Uniformat:B10,0,0,0,0,0,0,7196
11,Classification:Uniformat:B1010,0,0,0,0,0,0,308
12,Classification:Uniformat:B1010350,0,0,0,0,0,0,6748
13,Classification:Uniformat:B1010400,0,0,0,0,0,0,70
14,Classification:Uniformat:B2010,0,0,0,0,0,0,812
15,Constraints,66793,0,0,0,0,556,19814
16,Constraints(Type),46,0,0,0,0,0,64
17,Construction,14646,0,0,0,0,192,5652
18,Construction(Type),4356,0,0,0,0,0,60
19,Cross-Section Definition,2284,0,0,0,0,0,442
20,DB Component Instance,0,0,422,1028,0,0,0
21,DB Part,0,52,3272,3072,0,0,0
22,DXF_DWG,0,4,0,0,0,0,0
23,Dimensions,70150,0,0,0,0,518,21460
24,Dimensions(Type),450,0,0,0,0,0,230
25,Energy Analysis,0,0,0,0,0,40,0
26,Geometric Position,29575,0,0,0,0,0,20186
27,Graphics,5890,0,0,0,0,42,476
28,Graphics(Type),647,0,0,0,0,0,84
29,Handrail 1(Type),2240,0,0,0,0,0,0
30,Handrail 2(Type),896,0,0,0,0,0,0
31,Horizontal Grid,0,0,0,0,0,10,0
32,IFC,48342,192,44998,10463,2198,646,11713
33,IFCAPPLICATION,0,3,3,3,3,3,3
34,IFCBEAMTYPE,16464,0,0,0,0,0,7536
35,IFCBUILDINGELEMENTPROXYTYPE,0,0,0,0,0,0,400
36,IFCCOLUMNTYPE,2460,0,0,0,0,0,432
37,IFCDOORLININGPROPERTIES,0,0,0,0,56,0,0
38,IFCDOORSTYLE,0,0,0,0,196,0,0
39,IFCFURNITURETYPE,0,0,0,0,610,0,0
40,IFCMATERIALLAYER,1311,0,0,0,91,7,75
41,IFCMATERIALLAYERSETUSAGE,7845,0,0,0,543,42,450
42,IFCMEMBERTYPE,532,0,0,0,0,0,0
43,IFCORGANIZATION,0,1,1,1,1,1,1
44,IFCOWNERHISTORY,0,3,3,3,2,2,2
45,IFCPERSON,0,3,3,3,1,1,1
46,IFCRAMPFLIGHTTYPE,24,0,0,0,0,0,0
47,IFCSLABTYPE,7948,0,0,0,0,0,864
48,IFCSTAIRFLIGHTTYPE,2660,0,0,0,0,0,0
49,IFCWALLTYPE,4568,0,0,0,0,0,464
50,IFCWINDOWLININGPROPERTIES,0,0,0,0,96,0,0
51,IFCWINDOWSTYLE,0,0,0,0,336,0,0
52,Identity Data,56180,0,0,0,0,200,18413
53,Identity Data(Type),2064,0,0,0,0,0,306
54,Instance Part Properties,0,961,189478,48568,0,0,0
55,Item,168780,1279,116307,46989,11637,1938,71389
56,Layers(Type),0,0,0,0,0,0,80
57,Mass Properties Configuration Context,0,78,18638,2024,0,0,0
58,Materials,0,332,56140,12970,0,0,0
59,Materials and Finishes,18176,0,0,0,0,88,4536
60,Materials and Finishes(Type),252,0,0,0,0,0,36
61,Other,64557,0,0,0,0,864,24458
62,Other(Type),2064,0,0,0,0,0,418
63,PSet_Revit_Analytical Model,0,0,0,0,156,0,0
64,PSet_Revit_Constraints,0,0,0,0,2835,0,0
65,PSet_Revit_Construction,0,0,0,0,68,0,0
66,PSet_Revit_Dimensions,0,0,0,0,991,0,0
67,PSet_Revit_Graphics,0,0,0,0,16,0,0
68,PSet_Revit_Identity Data,0,0,0,0,204,0,0
69,PSet_Revit_Materials and Finishes,0,0,0,0,32,0,0
70,PSet_Revit_Other,0,0,0,0,3208,0,0
71,PSet_Revit_Phasing,0,0,0,0,860,0,0
72,PSet_Revit_Structural,0,0,0,0,470,0,0
73,PSet_Revit_Structural Analysis,0,0,0,0,364,0,0
74,PSet_Revit_Type_Constraints,0,0,0,0,8,0,0
75,PSet_Revit_Type_Construction,0,0,0,0,1244,0,0
76,PSet_Revit_Type_Dimensions,0,0,0,0,1230,0,0
77,PSet_Revit_Type_Graphics,0,0,0,0,412,0,0
78,PSet_Revit_Type_Identity Data,0,0,0,0,1354,0,0
79,PSet_Revit_Type_Materials and Finishes,0,0,0,0,726,0,0
80,PSet_Revit_Type_Other,0,0,0,0,11857,0,0
81,PSet_Revit_Type_Risers,0,0,0,0,14,0,0
82,PSet_Revit_Type_Stringers,0,0,0,0,20,0,0
83,PSet_Revit_Type_Structural,0,0,0,0,76,0,0
84,PSet_Revit_Type_Treads,0,0,0,0,12,0,0
85,Pattern,0,0,0,0,0,0,532
86,Phasing,18590,0,0,0,0,236,5036
87,ProfileProperties,4476,0,0,0,0,0,0
88,Pset_AirSideSystemInformation,46,0,0,0,0,0,24
89,Pset_BeamCommon,24696,0,0,0,96,0,11304
90,Pset_BuildingCommon,3,0,0,0,2,3,3
91,Pset_BuildingElementProxyCommon,0,0,0,0,0,0,200
92,Pset_BuildingStoreyCommon,46,0,0,0,0,4,24
93,Pset_ColumnCommon,2462,0,0,0,0,0,434
94,Pset_CoveringCommon,0,0,0,0,78,24,0
95,Pset_CurtainWallCommon,0,0,0,0,0,6,0
96,Pset_DoorCommon,0,0,0,0,112,22,0
97,Pset_ElementShading,5254,0,0,0,0,0,356
98,Pset_ManufacturerTypeInformation,0,0,0,0,0,28,0
99,Pset_MemberCommon,750,0,0,0,0,200,0
100,Pset_PlateCommon,24,0,0,0,0,60,0
101,Pset_ProductRequirements,18753,0,0,0,0,0,5076
102,Pset_ProvisionForVoid,0,0,0,0,0,0,100
103,Pset_QuantityTakeOff,18682,0,0,0,0,0,5036
104,Pset_RailingCommon,1792,0,0,0,32,0,0
105,Pset_RampCommon,306,0,0,0,0,0,0
106,Pset_RampFlightCommon,110,0,0,0,0,0,0
107,Pset_ReinforcementBarCountOfIndependentFooting,0,0,0,0,0,0,36
108,Pset_ReinforcementBarPitchOfBeam,8232,0,0,0,0,0,3768
109,Pset_ReinforcementBarPitchOfColumn,1230,0,0,0,0,0,216
110,Pset_ReinforcementBarPitchOfContinuousFooting,0,0,0,0,0,0,36
111,Pset_ReinforcementBarPitchOfSlab,3966,0,0,0,0,0,482
112,Pset_ReinforcementBarPitchOfWall,3426,0,0,0,0,0,348
113,Pset_RoofCommon,0,0,0,0,5,12,0
114,Pset_SlabCommon,9437,0,0,0,160,24,824
115,Pset_SpaceCommon,0,0,0,0,44,6,0
116,Pset_StairCommon,637,0,0,0,14,0,0
117,Pset_StairFlightCommon,6648,0,0,0,44,0,0
118,Pset_WallCommon,5710,0,0,0,570,48,696
119,Pset_WindowCommon,0,0,0,0,192,32,0
120,Quantities,44,0,0,0,44,158,0
121,Risers,3325,0,0,0,0,0,0
122,Rolled-Up Mass Properties,0,0,3416,2592,0,0,0
123,Routing System Defined,0,0,0,4,0,0,0
124,Slab Shape Edit,4,0,0,0,0,0,4
125,Structural,55896,0,0,0,0,52,12390
126,Structural Analysis,4851,0,0,0,0,0,12090
127,Structural Section Geometry,3528,0,0,0,0,0,7576
128,Structural(Type),0,0,0,0,0,0,36
129,Supports(Type),649,0,0,0,0,0,0
130,Text,6,0,0,0,0,0,0
131,Top Rail(Type),1395,0,0,0,0,0,0
132,Treads,4321,0,0,0,0,0,0
133,Vertical Grid,0,0,0,0,0,10,0
134,empty property set name,0,110,24036,6786,0,0,0
135,owning_user,0,56,13596,3132,0,0,0

Overall category roll-up:

,Category,Files Present,Total Entries
0,Item,7,418319
1,IFC,7,118552
2,IFCAPPLICATION,6,18
3,IFCOWNERHISTORY,6,15
4,IFCPERSON,6,12
5,IFCORGANIZATION,6,6
6,Pset_SlabCommon,4,10445
7,IFCMATERIALLAYERSETUSAGE,4,8880
8,Pset_WallCommon,4,7024
9,IFCMATERIALLAYER,4,1484
10,Pset_BuildingCommon,4,11
11,Instance Part Properties,3,239007
12,Dimensions,3,92128
13,Other,3,89879
14,Constraints,3,87163
15,Identity Data,3,74793
16,ABB4HVDCDesignRevision,3,71574
17,Materials,3,69442
18,Structural,3,68338
19,ABB4HVDCDesign,3,48824
20,Pset_BeamCommon,3,36096
21,empty property set name,3,30932
22,Phasing,3,23862
23,Materials and Finishes,3,22800
24,Mass Properties Configuration Context,3,20740
25,Construction,3,20490
26,owning_user,3,16784
27,Analytical Properties,3,8991
28,Graphics,3,6408
29,DB Part,3,6396
30,ABB4ModelRevision Master,3,5068
31,Quantities,3,246
32,Pset_BuildingStoreyCommon,3,74
33,Geometric Position,2,49761
34,IFCBEAMTYPE,2,24000
35,Pset_ProductRequirements,2,23829
36,Pset_QuantityTakeOff,2,23718
37,Structural Analysis,2,16941
38,Pset_ReinforcementBarPitchOfBeam,2,12000
39,Structural Section Geometry,2,11104
40,IFCSLABTYPE,2,8812
41,Pset_StairFlightCommon,2,6692
42,Rolled-Up Mass Properties,2,6008
43,Pset_ElementShading,2,5610
44,IFCWALLTYPE,2,5032
45,Pset_ReinforcementBarPitchOfSlab,2,4448
46,Construction(Type),2,4416
47,Pset_ReinforcementBarPitchOfWall,2,3774
48,Pset_ColumnCommon,2,2896
49,IFCCOLUMNTYPE,2,2892
50,Cross-Section Definition,2,2726
51,Other(Type),2,2482
52,Identity Data(Type),2,2370
53,Pset_RailingCommon,2,1824
54,DB Component Instance,2,1450
55,Pset_ReinforcementBarPitchOfColumn,2,1446
56,Pset_MemberCommon,2,950
57,Graphics(Type),2,731
58,Dimensions(Type),2,680
59,Pset_StairCommon,2,651
60,Materials and Finishes(Type),2,288
61,Pset_WindowCommon,2,224
62,Pset_DoorCommon,2,134
63,Constraints(Type),2,110
64,Pset_CoveringCommon,2,102
65,Pset_PlateCommon,2,84
66,Pset_AirSideSystemInformation,2,70
67,Pset_SpaceCommon,2,50
68,Pset_RoofCommon,2,17
69,Slab Shape Edit,2,8
70,PSet_Revit_Type_Other,1,11857
71,Classification:Uniformat:B10,1,7196
72,Classification:Uniformat:B1010350,1,6748
73,ProfileProperties,1,4476
74,Treads,1,4321
75,Risers,1,3325
76,PSet_Revit_Other,1,3208
77,PSet_Revit_Constraints,1,2835
78,IFCSTAIRFLIGHTTYPE,1,2660
79,Handrail 1(Type),1,2240
80,Top Rail(Type),1,1395
81,PSet_Revit_Type_Identity Data,1,1354
82,PSet_Revit_Type_Construction,1,1244
83,PSet_Revit_Type_Dimensions,1,1230
84,Classification:Uniformat:A1010100,1,1078
85,PSet_Revit_Dimensions,1,991
86,Handrail 2(Type),1,896
87,PSet_Revit_Phasing,1,860
88,Classification:Uniformat:B2010,1,812
89,PSet_Revit_Type_Materials and Finishes,1,726
90,Supports(Type),1,649
91,IFCFURNITURETYPE,1,610
92,IFCMEMBERTYPE,1,532
93,Pattern,1,532
94,PSet_Revit_Structural,1,470
95,PSet_Revit_Type_Graphics,1,412
96,IFCBUILDINGELEMENTPROXYTYPE,1,400
97,Calculation Rules(Type),1,364
98,PSet_Revit_Structural Analysis,1,364
99,IFCWINDOWSTYLE,1,336
100,Classification:Uniformat:B1010,1,308
101,Pset_RampCommon,1,306
102,PSet_Revit_Identity Data,1,204
103,Pset_BuildingElementProxyCommon,1,200
104,IFCDOORSTYLE,1,196
105,PSet_Revit_Analytical Model,1,156
106,Classification:Uniformat:A1010110,1,126
107,Pset_RampFlightCommon,1,110
108,Pset_ProvisionForVoid,1,100
109,IFCWINDOWLININGPROPERTIES,1,96
110,Layers(Type),1,80
111,PSet_Revit_Type_Structural,1,76
112,Analysis Results,1,74
113,Classification:Uniformat:B1010400,1,70
114,PSet_Revit_Construction,1,68
115,Classification:Uniformat Classification,1,56
116,IFCDOORLININGPROPERTIES,1,56
117,Energy Analysis,1,40
118,Pset_ReinforcementBarCountOfIndependentFooting,1,36
119,Pset_ReinforcementBarPitchOfContinuousFooting,1,36
120,Structural(Type),1,36
121,PSet_Revit_Materials and Finishes,1,32
122,Pset_ManufacturerTypeInformation,1,28
123,IFCRAMPFLIGHTTYPE,1,24
124,PSet_Revit_Type_Stringers,1,20
125,Adaptive Component,1,16
126,PSet_Revit_Graphics,1,16
127,PSet_Revit_Type_Risers,1,14
128,PSet_Revit_Type_Treads,1,12
129,Horizontal Grid,1,10
130,Vertical Grid,1,10
131,PSet_Revit_Type_Constraints,1,8
132,Pset_CurtainWallCommon,1,6
133,Text,1,6
134,DXF_DWG,1,4
135,Routing System Defined,1,4

Total unique categories across JSON_Edit: 136