In [5]:
from pathlib import Path
import json
import pandas as pd

# Display settings (optional)
pd.set_option('display.max_colwidth', 120)

# How many rows to show when displaying DataFrames in the notebook
pd.set_option('display.max_rows', 200)  # increase if you want more
pd.set_option('display.min_rows', 50)

In [6]:
# Choose the input JSON file (JSON Whole Model export)
file_name = "ASTIDC-STAN-HE-EPD-MVB1-M-E-0002.json"

# Default: workspace-root/JSON Whole Model/<file_name> (works when notebook is in PyDataTransform/)
input_path = (Path('..') / 'JSON Whole Model' / file_name).resolve()
if not input_path.exists():
    input_path = (Path('JSON Whole Model') / file_name).resolve()

assert input_path.exists(), f"File not found: {input_path}"

# 1) Copy the JSON being read into JSON_Edit
json_edit_dir = (Path('..') / 'JSON_Edit').resolve()
if not json_edit_dir.exists():
    json_edit_dir = (Path('JSON_Edit')).resolve()
json_edit_dir.mkdir(parents=True, exist_ok=True)

copied_path = json_edit_dir / input_path.name
copied_path.write_text(input_path.read_text(encoding='utf-8'), encoding='utf-8')
print(f"Copied source JSON to: {copied_path}")

# Keep original JSON structure in memory so we can write it back without escaping '/'
with copied_path.open('r', encoding='utf-8') as f:
    records = json.load(f)

df = pd.DataFrame(records)
working_json_path = copied_path
df.shape

Copied source JSON to: C:\Git\APS-IFC\JSON_Edit\ASTIDC-STAN-HE-EPD-MVB1-M-E-0002.json

(180, 4)

#### Model element Name counts
This notebook loads a `JSON Whole Model/*.json` export and prints a table with **Name**, **DbId**, **GUID**, and the **total count of that Name** across the model (duplicates included).

In [7]:
def _extract_guid(props):
    # `props` is the element's `Properties` array.
    # We look for the entry with displayName == 'GUID' (case-insensitive).
    if not isinstance(props, list):
        return None
    for item in props:
        if not isinstance(item, dict):
            continue
        display_name = str(item.get('displayName', '')).strip()
        if display_name.lower() == 'guid':
            return item.get('value')
    return None

def _strip_guid_prefix(name):
    if pd.isna(name):
        return name
    text = str(name)
    if '_' not in text:
        return text

    prefix, rest = text.split('_', 1)
    # Remove prefixes like "1JNL9441111_" / "1JNL9442575_" (or similar ID-like prefixes)
    if len(prefix) >= 8 and any(ch.isdigit() for ch in prefix):
        return rest
    return text

def _write_json_unescaped(path, payload):
    # Python json.dumps keeps slashes as '/' (does not force '\\/')
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding='utf-8')

# 2 & 3) Clean the Name column by removing GUID-like prefixes
df['Name'] = df['Name'].apply(_strip_guid_prefix)

# Sync cleaned names back to original JSON records
for idx, item in enumerate(records):
    if idx < len(df):
        item['Name'] = None if pd.isna(df.at[idx, 'Name']) else str(df.at[idx, 'Name'])

# Save amended JSON into JSON_Edit (does not change original source file)
_write_json_unescaped(working_json_path, records)
print(f"Updated JSON written to: {working_json_path}")

# Build GUID + key columns (GUID is primary unique key for matching)
df['GUID'] = df['Properties'].apply(_extract_guid)
df['ElementKey'] = df['GUID'].fillna(df['ExternalId'])
name_counts = df['Name'].value_counts(dropna=False)
df['NameCount'] = df['Name'].map(name_counts)

guid_duplicates = df['GUID'].dropna().duplicated().sum()
print(f"GUID duplicates found: {guid_duplicates}")

table = (
    df[['ElementKey', 'GUID', 'ExternalId', 'Name', 'DbId', 'NameCount']]
    .sort_values(['Name', 'DbId'], kind='stable')
    .reset_index(drop=True)
)

# 4) Print out the updated table
rows_to_show = 50  # set to None to show all rows (can be slow/huge)
table if rows_to_show is None else table.head(rows_to_show)

Updated JSON written to: C:\Git\APS-IFC\JSON_Edit\ASTIDC-STAN-HE-EPD-MVB1-M-E-0002.json
GUID duplicates found: 0

,ElementKey,GUID,ExternalId,Name,DbId,NameCount
0,8d3567ff-612b-3878-a628-4b9d838df628,8d3567ff-612b-3878-a628-4b9d838df628,0/0/1,A-1JNL9322340 - Pyramid,5,1
1,c9232a6d-75c5-3739-a3c2-3777ac67e597,c9232a6d-75c5-3739-a3c2-3777ac67e597,0/0/2/1/2,A-Cable Ladder 90 450,14,3
2,3d931300-8be8-3a23-a464-9cedb7d98460,3d931300-8be8-3a23-a464-9cedb7d98460,0/0/2/1/3,A-Cable Ladder 90 450,15,3
3,19f22aef-af24-3a1c-b63f-1703e94e50ba,19f22aef-af24-3a1c-b63f-1703e94e50ba,0/0/2/1/7,A-Cable Ladder 90 450,19,3
4,167265d4-c3e5-3071-b189-599004f7b9f3,167265d4-c3e5-3071-b189-599004f7b9f3,0/0/2/1/0,A-Cable Ladder MVS,12,9
5,366c5df3-80dd-34c1-95f6-f69c55125c61,366c5df3-80dd-34c1-95f6-f69c55125c61,0/0/2/1/1,A-Cable Ladder MVS,13,9
6,5b00d1af-e807-3f5e-bc90-b4ab1b39b423,5b00d1af-e807-3f5e-bc90-b4ab1b39b423,0/0/2/1/4,A-Cable Ladder MVS,16,9
7,69eed907-29dc-3444-89dd-6e9fe484ce1b,69eed907-29dc-3444-89dd-6e9fe484ce1b,0/0/2/1/5,A-Cable Ladder MVS,17,9
8,97558d3b-c88d-3c4c-b66f-b2109faa27c0,97558d3b-c88d-3c4c-b66f-b2109faa27c0,0/0/2/1/6,A-Cable Ladder MVS,18,9
9,a378d9c0-1349-32e1-9dad-1b5310fafdc9,a378d9c0-1349-32e1-9dad-1b5310fafdc9,0/0/2/1/8,A-Cable Ladder MVS,20,9
10,e850826a-a5ad-37b1-9e43-da3a757b49af,e850826a-a5ad-37b1-9e43-da3a757b49af,0/0/2/1/9,A-Cable Ladder MVS,21,9
11,d58d58b8-74eb-36e1-8edb-0af9b1129293,d58d58b8-74eb-36e1-8edb-0af9b1129293,0/0/2/1/10,A-Cable Ladder MVS,22,9
12,9c0b638e-d014-3013-ade3-f83270326350,9c0b638e-d014-3013-ade3-f83270326350,0/0/2/1/11,A-Cable Ladder MVS,23,9
13,cd06ec2a-dde8-35e7-bb84-94eaba646aaa,cd06ec2a-dde8-35e7-bb84-94eaba646aaa,0/0/2,"A-Electrical design requirements, MVS1, NER, Aux Tx-building, Cable ways",6,1
14,c91648b7-3272-3ce6-92e1-f4279dbf9478,c91648b7-3272-3ce6-92e1-f4279dbf9478,0/0/2/0,A-K6 cable tray MVS P1,9,1
15,76440f25-e447-3cc5-958e-8727a44d872d,76440f25-e447-3cc5-958e-8727a44d872d,0/0/2/1,A-MVS Cable Ladder P1,10,1
16,b68858ba-08a3-5823-ab81-f132bb34e8f1,b68858ba-08a3-5823-ab81-f132bb34e8f1,a,ASTIDC-STAN-HE-EPD-MVB1-M-E-0002.ifc,1,1
17,0/0/1/0,None,0/0/1/0,Body,8,161
18,0/0/2/0/0,None,0/0/2/0/0,Body,11,161
19,0/0/2/1/0/0,None,0/0/2/1/0/0,Body,24,161
20,0/0/2/1/0/0/0,None,0/0/2/1/0/0/0,Body,25,161
21,0/0/2/1/0/0/0/0,None,0/0/2/1/0/0/0/0,Body,26,161
22,0/0/2/1/0/0/0/1,None,0/0/2/1/0/0/0/1,Body,27,161
23,0/0/2/1/0/0/0/2,None,0/0/2/1/0/0/0/2,Body,28,161
24,0/0/2/1/0/0/0/3,None,0/0/2/1/0/0/0/3,Body,29,161
25,0/0/2/1/0/0/0/4,None,0/0/2/1/0/0/0/4,Body,30,161
26,0/0/2/1/0/0/0/5,None,0/0/2/1/0/0/0/5,Body,31,161
27,0/0/2/1/0/0/0/6,None,0/0/2/1/0/0/0/6,Body,32,161
28,0/0/2/1/0/0/0/7,None,0/0/2/1/0/0/0/7,Body,33,161
29,0/0/2/1/0/0/0/8,None,0/0/2/1/0/0/0/8,Body,34,161
30,0/0/2/1/0/0/0/9,None,0/0/2/1/0/0/0/9,Body,35,161
31,0/0/2/1/0/0/0/10,None,0/0/2/1/0/0/0/10,Body,36,161
32,0/0/2/1/0/0/0/11,None,0/0/2/1/0/0/0/11,Body,37,161
33,0/0/2/1/0/0/0/12,None,0/0/2/1/0/0/0/12,Body,38,161
34,0/0/2/1/0/0/0/13,None,0/0/2/1/0/0/0/13,Body,39,161
35,0/0/2/1/0/0/0/14,None,0/0/2/1/0/0/0/14,Body,40,161
36,0/0/2/1/0/0/0/15,None,0/0/2/1/0/0/0/15,Body,41,161
37,0/0/2/1/0/0/0/16,None,0/0/2/1/0/0/0/16,Body,42,161
38,0/0/2/1/1/0,None,0/0/2/1/1/0,Body,43,161
39,0/0/2/1/1/0/0,None,0/0/2/1/1/0/0,Body,44,161
40,0/0/2/1/1/0/0/0,None,0/0/2/1/1/0/0/0,Body,45,161
41,0/0/2/1/1/0/0/1,None,0/0/2/1/1/0/0/1,Body,46,161
42,0/0/2/1/1/0/0/2,None,0/0/2/1/1/0/0/2,Body,47,161
43,0/0/2/1/2/0,None,0/0/2/1/2/0,Body,48,161
44,0/0/2/1/2/0/0,None,0/0/2/1/2/0/0,Body,49,161
45,0/0/2/1/2/0/0/0,None,0/0/2/1/2/0/0/0,Body,50,161
46,0/0/2/1/2/0/0/1,None,0/0/2/1/2/0/0/1,Body,51,161
47,0/0/2/1/2/0/0/2,None,0/0/2/1/2/0/0/2,Body,52,161
48,0/0/2/1/2/0/0/3,None,0/0/2/1/2/0/0/3,Body,53,161
49,0/0/2/1/2/0/0/4,None,0/0/2/1/2/0/0/4,Body,54,161

In [8]:
# Export the table
out_dir = input_path.parent
# csv_path = out_dir / f"{input_path.stem}_name_table.csv"
xlsx_path = out_dir / f"{input_path.stem}_name_table.xlsx"

# table.to_csv(csv_path, index=False, encoding='utf-8-sig')
# print("Wrote CSV:", csv_path)

# Excel export requires openpyxl (recommended)
try:
    import openpyxl  # noqa: F401
    table.to_excel(xlsx_path, index=False)
    print("Wrote Excel:", xlsx_path)
except ImportError:
    print("Excel export skipped: package 'openpyxl' is not installed.")
    print("Run: pip install openpyxl  (or use notebook package install), then re-run this cell.")

Wrote Excel: C:\Git\APS-IFC\JSON Whole Model\ASTIDC-STAN-HE-EPD-MVB1-M-E-0002_name_table.xlsx

In [9]:
def _strip_object_prefix(value):
    if not isinstance(value, str):
        return value
    if '_' not in value:
        return value
    prefix, rest = value.split('_', 1)
    if len(prefix) >= 8 and any(ch.isdigit() for ch in prefix):
        return rest
    return value

property_changes = []
objects_changed = 0

for idx, row in df.iterrows():
    object_changed = False
    rec = records[idx] if idx < len(records) else None

    guid = row.get('GUID')
    external_id = row.get('ExternalId')

    cleaned_name = _strip_object_prefix(row.get('Name'))
    if cleaned_name != row.get('Name'):
        df.at[idx, 'Name'] = cleaned_name
        if isinstance(rec, dict):
            rec['Name'] = cleaned_name
        object_changed = True

    props = rec.get('Properties') if isinstance(rec, dict) else row.get('Properties')
    if isinstance(props, list):
        for prop in props:
            if not isinstance(prop, dict):
                continue
            old_value = prop.get('value')
            new_value = _strip_object_prefix(old_value)
            if new_value != old_value:
                prop['value'] = new_value
                object_changed = True
                property_changes.append({
                    'GUID': guid,
                    'ExternalId': external_id,
                    'ObjectName': cleaned_name,
                    'DbId': row.get('DbId'),
                    'Property': prop.get('displayName'),
                    'OldValue': old_value,
                    'NewValue': new_value
                })

    if object_changed:
        objects_changed += 1

# Keep '/' in values such as ExternalId (no escaped '\\/')
_write_json_unescaped(working_json_path, records)
print(f"Updated JSON written to: {working_json_path}")

if property_changes:
    changes_df = pd.DataFrame(property_changes)
    print("\nChanged object-property values (matched by GUID first):")
    display(changes_df[['GUID', 'ExternalId', 'ObjectName', 'DbId', 'Property', 'OldValue', 'NewValue']])
else:
    print("\nNo prefixed property values found.")

print(f"\nTotal objects changed: {objects_changed}")
print(f"Total property values changed: {len(property_changes)}")

Updated JSON written to: C:\Git\APS-IFC\JSON_Edit\ASTIDC-STAN-HE-EPD-MVB1-M-E-0002.json

Changed object-property values (matched by GUID first):

,GUID,ExternalId,ObjectName,DbId,Property,OldValue,NewValue
0,8d3567ff-612b-3878-a628-4b9d838df628,0/0/1,A-1JNL9322340 - Pyramid,5,Name,1JNL9322340_A-1JNL9322340 - Pyramid,A-1JNL9322340 - Pyramid
1,8d3567ff-612b-3878-a628-4b9d838df628,0/0/1,A-1JNL9322340 - Pyramid,5,NAME,1JNL9322340_A-1JNL9322340 - Pyramid,A-1JNL9322340 - Pyramid
2,8d3567ff-612b-3878-a628-4b9d838df628,0/0/1,A-1JNL9322340 - Pyramid,5,OBJECTTYPE,1JNL9322340_A-1JNL9322340 - Pyramid,A-1JNL9322340 - Pyramid
3,8d3567ff-612b-3878-a628-4b9d838df628,0/0/1,A-1JNL9322340 - Pyramid,5,GLOBALID,1TQoQ3fqOqqfozt5n_JZ7X,JZ7X
4,8d3567ff-612b-3878-a628-4b9d838df628,0/0/1,A-1JNL9322340 - Pyramid,5,Name,1JNL9322340_A-1JNL9322340 - Pyramid,A-1JNL9322340 - Pyramid
5,cd06ec2a-dde8-35e7-bb84-94eaba646aaa,0/0/2,"A-Electrical design requirements, MVS1, NER, Aux Tx-building, Cable ways",6,Name,"1JNL9362899_A-Electrical design requirements, MVS1, NER, Aux Tx-building, Cable ways","A-Electrical design requirements, MVS1, NER, Aux Tx-building, Cable ways"
6,cd06ec2a-dde8-35e7-bb84-94eaba646aaa,0/0/2,"A-Electrical design requirements, MVS1, NER, Aux Tx-building, Cable ways",6,NAME,"1JNL9362899_A-Electrical design requirements, MVS1, NER, Aux Tx-building, Cable ways","A-Electrical design requirements, MVS1, NER, Aux Tx-building, Cable ways"
7,cd06ec2a-dde8-35e7-bb84-94eaba646aaa,0/0/2,"A-Electrical design requirements, MVS1, NER, Aux Tx-building, Cable ways",6,OBJECTTYPE,"1JNL9362899_A-Electrical design requirements, MVS1, NER, Aux Tx-building, Cable ways","A-Electrical design requirements, MVS1, NER, Aux Tx-building, Cable ways"
8,cd06ec2a-dde8-35e7-bb84-94eaba646aaa,0/0/2,"A-Electrical design requirements, MVS1, NER, Aux Tx-building, Cable ways",6,GLOBALID,1YNBYXeuaxse$_5RIiDq3M,5RIiDq3M
9,c9232a6d-75c5-3739-a3c2-3777ac67e597,0/0/2/1/2,A-Cable Ladder 90 450,14,Name,1JNL9441111_A-Cable Ladder 90 450,A-Cable Ladder 90 450
10,c9232a6d-75c5-3739-a3c2-3777ac67e597,0/0/2/1/2,A-Cable Ladder 90 450,14,GLOBALID,398ofjTSKtEQF2DtUiP_MN,MN
11,c9232a6d-75c5-3739-a3c2-3777ac67e597,0/0/2/1/2,A-Cable Ladder 90 450,14,NAME,1JNL9441111_A-Cable Ladder 90 450,A-Cable Ladder 90 450
12,c9232a6d-75c5-3739-a3c2-3777ac67e597,0/0/2/1/2,A-Cable Ladder 90 450,14,OBJECTTYPE,1JNL9441111_A-Cable Ladder 90 450,A-Cable Ladder 90 450
13,c9232a6d-75c5-3739-a3c2-3777ac67e597,0/0/2/1/2,A-Cable Ladder 90 450,14,GLOBALID,3lR7$VA0axQfm_aoAOQaAY,aoAOQaAY
14,c9232a6d-75c5-3739-a3c2-3777ac67e597,0/0/2/1/2,A-Cable Ladder 90 450,14,Name,1JNL9441111_A-Cable Ladder 90 450,A-Cable Ladder 90 450
15,c9232a6d-75c5-3739-a3c2-3777ac67e597,0/0/2/1/2,A-Cable Ladder 90 450,14,GLOBALID,2A7cFaVcayExGHxefL5_$4,$4
16,c9232a6d-75c5-3739-a3c2-3777ac67e597,0/0/2/1/2,A-Cable Ladder 90 450,14,GLOBALID,0$Aq$D1pKrzRdtUJ0G_Epl,Epl
17,c9232a6d-75c5-3739-a3c2-3777ac67e597,0/0/2/1/2,A-Cable Ladder 90 450,14,GLOBALID,1tGj5chWOxKgW1PiSbTAG_,
18,3d931300-8be8-3a23-a464-9cedb7d98460,0/0/2/1/3,A-Cable Ladder 90 450,15,Name,1JNL9441111_A-Cable Ladder 90 450,A-Cable Ladder 90 450
19,3d931300-8be8-3a23-a464-9cedb7d98460,0/0/2/1/3,A-Cable Ladder 90 450,15,NAME,1JNL9441111_A-Cable Ladder 90 450,A-Cable Ladder 90 450
20,3d931300-8be8-3a23-a464-9cedb7d98460,0/0/2/1/3,A-Cable Ladder 90 450,15,OBJECTTYPE,1JNL9441111_A-Cable Ladder 90 450,A-Cable Ladder 90 450
21,3d931300-8be8-3a23-a464-9cedb7d98460,0/0/2/1/3,A-Cable Ladder 90 450,15,Name,1JNL9441111_A-Cable Ladder 90 450,A-Cable Ladder 90 450
22,3d931300-8be8-3a23-a464-9cedb7d98460,0/0/2/1/3,A-Cable Ladder 90 450,15,GLOBALID,3$UtogwgKu4gYN0_mL9$uF,mL9$uF
23,3d931300-8be8-3a23-a464-9cedb7d98460,0/0/2/1/3,A-Cable Ladder 90 450,15,GLOBALID,1J2INASauvc8VY1FX_iUbr,iUbr
24,3d931300-8be8-3a23-a464-9cedb7d98460,0/0/2/1/3,A-Cable Ladder 90 450,15,GLOBALID,2UClV6KoO_GgPmEVkLSFTJ,GgPmEVkLSFTJ
25,3d931300-8be8-3a23-a464-9cedb7d98460,0/0/2/1/3,A-Cable Ladder 90 450,15,GLOBALID,34yGysOl4olwWtQH_g6hAz,g6hAz
26,19f22aef-af24-3a1c-b63f-1703e94e50ba,0/0/2/1/7,A-Cable Ladder 90 450,19,Name,1JNL9441111_A-Cable Ladder 90 450,A-Cable Ladder 90 450
27,19f22aef-af24-3a1c-b63f-1703e94e50ba,0/0/2/1/7,A-Cable Ladder 90 450,19,NAME,1JNL9441111_A-Cable Ladder 90 450,A-Cable Ladder 90 450
28,19f22aef-af24-3a1c-b63f-1703e94e50ba,0/0/2/1/7,A-Cable Ladder 90 450,19,OBJECTTYPE,1JNL9441111_A-Cable Ladder 90 450,A-Cable Ladder 90 450
29,19f22aef-af24-3a1c-b63f-1703e94e50ba,0/0/2/1/7,A-Cable Ladder 90 450,19,Name,1JNL9441111_A-Cable Ladder 90 450,A-Cable Ladder 90 450
30,19f22aef-af24-3a1c-b63f-1703e94e50ba,0/0/2/1/7,A-Cable Ladder 90 450,19,GLOBALID,28Y4wj5zmxjOGTbaJIsDJ_,
31,19f22aef-af24-3a1c-b63f-1703e94e50ba,0/0/2/1/7,A-Cable Ladder 90 450,19,GLOBALID,1tz8yy2vS_9f2vapzE1XTJ,9f2vapzE1XTJ
32,76440f25-e447-3cc5-958e-8727a44d872d,0/0/2/1,A-MVS Cable Ladder P1,10,Name,1JNL9442575_A-MVS Cable Ladder P1,A-MVS Cable Ladder P1
33,76440f25-e447-3cc5-958e-8727a44d872d,0/0/2/1,A-MVS Cable Ladder P1,10,NAME,1JNL9442575_A-MVS Cable Ladder P1,A-MVS Cable Ladder P1
34,76440f25-e447-3cc5-958e-8727a44d872d,0/0/2/1,A-MVS Cable Ladder P1,10,OBJECTTYPE,1JNL9442575_A-MVS Cable Ladder P1,A-MVS Cable Ladder P1
35,c91648b7-3272-3ce6-92e1-f4279dbf9478,0/0/2/0,A-K6 cable tray MVS P1,9,Name,1JNL9442576_A-K6 cable tray MVS P1,A-K6 cable tray MVS P1
36,c91648b7-3272-3ce6-92e1-f4279dbf9478,0/0/2/0,A-K6 cable tray MVS P1,9,NAME,1JNL9442576_A-K6 cable tray MVS P1,A-K6 cable tray MVS P1
37,c91648b7-3272-3ce6-92e1-f4279dbf9478,0/0/2/0,A-K6 cable tray MVS P1,9,OBJECTTYPE,1JNL9442576_A-K6 cable tray MVS P1,A-K6 cable tray MVS P1
38,c91648b7-3272-3ce6-92e1-f4279dbf9478,0/0/2/0,A-K6 cable tray MVS P1,9,Name,1JNL9442576_A-K6 cable tray MVS P1,A-K6 cable tray MVS P1
39,c91648b7-3272-3ce6-92e1-f4279dbf9478,0/0/2/0,A-K6 cable tray MVS P1,9,GLOBALID,0NPDHWVTyqARgvkA2Dhh_D,D
40,c91648b7-3272-3ce6-92e1-f4279dbf9478,0/0/2/0,A-K6 cable tray MVS P1,9,GLOBALID,1RygEHVzy_xw8ZDNOtIa1S,xw8ZDNOtIa1S
41,366c5df3-80dd-34c1-95f6-f69c55125c61,0/0/2/1/1,A-Cable Ladder MVS,13,Name,1JNL9442631_A-Cable Ladder MVS,A-Cable Ladder MVS
42,366c5df3-80dd-34c1-95f6-f69c55125c61,0/0/2/1/1,A-Cable Ladder MVS,13,NAME,1JNL9442631_A-Cable Ladder MVS,A-Cable Ladder MVS
43,366c5df3-80dd-34c1-95f6-f69c55125c61,0/0/2/1/1,A-Cable Ladder MVS,13,OBJECTTYPE,1JNL9442631_A-Cable Ladder MVS,A-Cable Ladder MVS
44,366c5df3-80dd-34c1-95f6-f69c55125c61,0/0/2/1/1,A-Cable Ladder MVS,13,Name,1JNL9442631_A-Cable Ladder MVS,A-Cable Ladder MVS
45,366c5df3-80dd-34c1-95f6-f69c55125c61,0/0/2/1/1,A-Cable Ladder MVS,13,GLOBALID,2LdMGD2$qt7eLQ5uekO9_J,J
46,366c5df3-80dd-34c1-95f6-f69c55125c61,0/0/2/1/1,A-Cable Ladder MVS,13,GLOBALID,0rdnkbHVa_TPwM3umsW6zP,TPwM3umsW6zP
47,69eed907-29dc-3444-89dd-6e9fe484ce1b,0/0/2/1/5,A-Cable Ladder MVS,17,Name,1JNL9442631_A-Cable Ladder MVS,A-Cable Ladder MVS
48,69eed907-29dc-3444-89dd-6e9fe484ce1b,0/0/2/1/5,A-Cable Ladder MVS,17,NAME,1JNL9442631_A-Cable Ladder MVS,A-Cable Ladder MVS
49,69eed907-29dc-3444-89dd-6e9fe484ce1b,0/0/2/1/5,A-Cable Ladder MVS,17,OBJECTTYPE,1JNL9442631_A-Cable Ladder MVS,A-Cable Ladder MVS
50,69eed907-29dc-3444-89dd-6e9fe484ce1b,0/0/2/1/5,A-Cable Ladder MVS,17,Name,1JNL9442631_A-Cable Ladder MVS,A-Cable Ladder MVS
51,69eed907-29dc-3444-89dd-6e9fe484ce1b,0/0/2/1/5,A-Cable Ladder MVS,17,GLOBALID,1uR3VObjqvxeikr_cuoG5y,cuoG5y
52,97558d3b-c88d-3c4c-b66f-b2109faa27c0,0/0/2/1/6,A-Cable Ladder MVS,18,Name,1JNL9442631_A-Cable Ladder MVS,A-Cable Ladder MVS
53,97558d3b-c88d-3c4c-b66f-b2109faa27c0,0/0/2/1/6,A-Cable Ladder MVS,18,NAME,1JNL9442631_A-Cable Ladder MVS,A-Cable Ladder MVS
54,97558d3b-c88d-3c4c-b66f-b2109faa27c0,0/0/2/1/6,A-Cable Ladder MVS,18,OBJECTTYPE,1JNL9442631_A-Cable Ladder MVS,A-Cable Ladder MVS
55,97558d3b-c88d-3c4c-b66f-b2109faa27c0,0/0/2/1/6,A-Cable Ladder MVS,18,Name,1JNL9442631_A-Cable Ladder MVS,A-Cable Ladder MVS
56,97558d3b-c88d-3c4c-b66f-b2109faa27c0,0/0/2/1/6,A-Cable Ladder MVS,18,GLOBALID,0$UPY8qXO_rBZtSVlVPRKs,rBZtSVlVPRKs
57,97558d3b-c88d-3c4c-b66f-b2109faa27c0,0/0/2/1/6,A-Cable Ladder MVS,18,GLOBALID,1xctFOB54sae$L_J_Ox266,J_Ox266
58,e850826a-a5ad-37b1-9e43-da3a757b49af,0/0/2/1/9,A-Cable Ladder MVS,21,Name,1JNL9442632_A-Cable Ladder MVS,A-Cable Ladder MVS
59,e850826a-a5ad-37b1-9e43-da3a757b49af,0/0/2/1/9,A-Cable Ladder MVS,21,NAME,1JNL9442632_A-Cable Ladder MVS,A-Cable Ladder MVS
60,e850826a-a5ad-37b1-9e43-da3a757b49af,0/0/2/1/9,A-Cable Ladder MVS,21,OBJECTTYPE,1JNL9442632_A-Cable Ladder MVS,A-Cable Ladder MVS
61,e850826a-a5ad-37b1-9e43-da3a757b49af,0/0/2/1/9,A-Cable Ladder MVS,21,Name,1JNL9442632_A-Cable Ladder MVS,A-Cable Ladder MVS
62,e850826a-a5ad-37b1-9e43-da3a757b49af,0/0/2/1/9,A-Cable Ladder MVS,21,GLOBALID,28ZVDhgAWyeA_QutZGGtEu,QutZGGtEu
63,e850826a-a5ad-37b1-9e43-da3a757b49af,0/0/2/1/9,A-Cable Ladder MVS,21,GLOBALID,0APjO3tzWoUun82Kik_7vQ,7vQ
64,d58d58b8-74eb-36e1-8edb-0af9b1129293,0/0/2/1/10,A-Cable Ladder MVS,22,Name,1JNL9442632_A-Cable Ladder MVS,A-Cable Ladder MVS
65,d58d58b8-74eb-36e1-8edb-0af9b1129293,0/0/2/1/10,A-Cable Ladder MVS,22,NAME,1JNL9442632_A-Cable Ladder MVS,A-Cable Ladder MVS
66,d58d58b8-74eb-36e1-8edb-0af9b1129293,0/0/2/1/10,A-Cable Ladder MVS,22,OBJECTTYPE,1JNL9442632_A-Cable Ladder MVS,A-Cable Ladder MVS
67,d58d58b8-74eb-36e1-8edb-0af9b1129293,0/0/2/1/10,A-Cable Ladder MVS,22,GLOBALID,30aesi3Ue_eRIxqVS$RQbu,eRIxqVS$RQbu
68,d58d58b8-74eb-36e1-8edb-0af9b1129293,0/0/2/1/10,A-Cable Ladder MVS,22,Name,1JNL9442632_A-Cable Ladder MVS,A-Cable Ladder MVS
69,d58d58b8-74eb-36e1-8edb-0af9b1129293,0/0/2/1/10,A-Cable Ladder MVS,22,GLOBALID,376WgFefGzNvX2g9apmJ1_,
70,d58d58b8-74eb-36e1-8edb-0af9b1129293,0/0/2/1/10,A-Cable Ladder MVS,22,GLOBALID,14SkNK1T4vpBGnwVVWy_Vc,Vc
71,9c0b638e-d014-3013-ade3-f83270326350,0/0/2/1/11,A-Cable Ladder MVS,23,Name,1JNL9442632_A-Cable Ladder MVS,A-Cable Ladder MVS
72,9c0b638e-d014-3013-ade3-f83270326350,0/0/2/1/11,A-Cable Ladder MVS,23,GLOBALID,2S2sEEq1Gm4wtZ_39mCcDG,39mCcDG
73,9c0b638e-d014-3013-ade3-f83270326350,0/0/2/1/11,A-Cable Ladder MVS,23,NAME,1JNL9442632_A-Cable Ladder MVS,A-Cable Ladder MVS
74,9c0b638e-d014-3013-ade3-f83270326350,0/0/2/1/11,A-Cable Ladder MVS,23,OBJECTTYPE,1JNL9442632_A-Cable Ladder MVS,A-Cable Ladder MVS
75,9c0b638e-d014-3013-ade3-f83270326350,0/0/2/1/11,A-Cable Ladder MVS,23,GLOBALID,22i6KQzWq_ivVl54MYaexE,ivVl54MYaexE
76,9c0b638e-d014-3013-ade3-f83270326350,0/0/2/1/11,A-Cable Ladder MVS,23,Name,1JNL9442632_A-Cable Ladder MVS,A-Cable Ladder MVS
77,9c0b638e-d014-3013-ade3-f83270326350,0/0/2/1/11,A-Cable Ladder MVS,23,GLOBALID,1YYXMGAy4wuRFEeq93i_5O,5O
78,9c0b638e-d014-3013-ade3-f83270326350,0/0/2/1/11,A-Cable Ladder MVS,23,GLOBALID,1sNiKwqVOvUAsxlQ$fA_RH,RH
79,167265d4-c3e5-3071-b189-599004f7b9f3,0/0/2/1/0,A-Cable Ladder MVS,12,Name,1JNL9442633_A-Cable Ladder MVS,A-Cable Ladder MVS
80,167265d4-c3e5-3071-b189-599004f7b9f3,0/0/2/1/0,A-Cable Ladder MVS,12,NAME,1JNL9442633_A-Cable Ladder MVS,A-Cable Ladder MVS
81,167265d4-c3e5-3071-b189-599004f7b9f3,0/0/2/1/0,A-Cable Ladder MVS,12,OBJECTTYPE,1JNL9442633_A-Cable Ladder MVS,A-Cable Ladder MVS
82,167265d4-c3e5-3071-b189-599004f7b9f3,0/0/2/1/0,A-Cable Ladder MVS,12,Name,1JNL9442633_A-Cable Ladder MVS,A-Cable Ladder MVS
83,167265d4-c3e5-3071-b189-599004f7b9f3,0/0/2/1/0,A-Cable Ladder MVS,12,GLOBALID,3D$qDNkUKo_PvZfjcsAJio,PvZfjcsAJio
84,167265d4-c3e5-3071-b189-599004f7b9f3,0/0/2/1/0,A-Cable Ladder MVS,12,GLOBALID,2Zu3Gvs34_pPyOHGX_igDX,pPyOHGX_igDX
85,5b00d1af-e807-3f5e-bc90-b4ab1b39b423,0/0/2/1/4,A-Cable Ladder MVS,16,Name,1JNL9442633_A-Cable Ladder MVS,A-Cable Ladder MVS
86,5b00d1af-e807-3f5e-bc90-b4ab1b39b423,0/0/2/1/4,A-Cable Ladder MVS,16,NAME,1JNL9442633_A-Cable Ladder MVS,A-Cable Ladder MVS
87,5b00d1af-e807-3f5e-bc90-b4ab1b39b423,0/0/2/1/4,A-Cable Ladder MVS,16,OBJECTTYPE,1JNL9442633_A-Cable Ladder MVS,A-Cable Ladder MVS
88,5b00d1af-e807-3f5e-bc90-b4ab1b39b423,0/0/2/1/4,A-Cable Ladder MVS,16,Name,1JNL9442633_A-Cable Ladder MVS,A-Cable Ladder MVS
89,5b00d1af-e807-3f5e-bc90-b4ab1b39b423,0/0/2/1/4,A-Cable Ladder MVS,16,GLOBALID,26SWyh6LiuOQRntyfSl_Q$,Q$
90,5b00d1af-e807-3f5e-bc90-b4ab1b39b423,0/0/2/1/4,A-Cable Ladder MVS,16,GLOBALID,0oQiAROR8qluh28GS_WhJu,WhJu
91,a378d9c0-1349-32e1-9dad-1b5310fafdc9,0/0/2/1/8,A-Cable Ladder MVS,20,Name,1JNL9442633_A-Cable Ladder MVS,A-Cable Ladder MVS
92,a378d9c0-1349-32e1-9dad-1b5310fafdc9,0/0/2/1/8,A-Cable Ladder MVS,20,GLOBALID,2ZUDd04qaouPsj6rCG_lt9,lt9
93,a378d9c0-1349-32e1-9dad-1b5310fafdc9,0/0/2/1/8,A-Cable Ladder MVS,20,NAME,1JNL9442633_A-Cable Ladder MVS,A-Cable Ladder MVS
94,a378d9c0-1349-32e1-9dad-1b5310fafdc9,0/0/2/1/8,A-Cable Ladder MVS,20,OBJECTTYPE,1JNL9442633_A-Cable Ladder MVS,A-Cable Ladder MVS
95,a378d9c0-1349-32e1-9dad-1b5310fafdc9,0/0/2/1/8,A-Cable Ladder MVS,20,Name,1JNL9442633_A-Cable Ladder MVS,A-Cable Ladder MVS
96,a378d9c0-1349-32e1-9dad-1b5310fafdc9,0/0/2/1/8,A-Cable Ladder MVS,20,GLOBALID,2TtPDuCHa_bxEg$NQsANXU,bxEg$NQsANXU
97,a378d9c0-1349-32e1-9dad-1b5310fafdc9,0/0/2/1/8,A-Cable Ladder MVS,20,GLOBALID,0S4grwB4q_Rhw05f94y4_$,Rhw05f94y4_$
98,None,0/0/1/0,Body,8,NAME,1JNL9322340_A-1JNL9322340 - Pyramid,A-1JNL9322340 - Pyramid
99,None,0/0/1/0,Body,8,OBJECTTYPE,1JNL9322340_A-1JNL9322340 - Pyramid,A-1JNL9322340 - Pyramid
100,None,0/0/1/0,Body,8,GLOBALID,1TQoQ3fqOqqfozt5n_JZ7X,JZ7X
101,None,0/0/1/0,Body,8,Name,1JNL9322340_A-1JNL9322340 - Pyramid,A-1JNL9322340 - Pyramid
102,None,0/0/2/0/0,Body,11,NAME,1JNL9442576_A-K6 cable tray MVS P1,A-K6 cable tray MVS P1
103,None,0/0/2/0/0,Body,11,OBJECTTYPE,1JNL9442576_A-K6 cable tray MVS P1,A-K6 cable tray MVS P1
104,None,0/0/2/0/0,Body,11,Name,1JNL9442576_A-K6 cable tray MVS P1,A-K6 cable tray MVS P1
105,None,0/0/2/0/0,Body,11,GLOBALID,0NPDHWVTyqARgvkA2Dhh_D,D
106,None,0/0/2/0/0,Body,11,GLOBALID,1RygEHVzy_xw8ZDNOtIa1S,xw8ZDNOtIa1S
107,None,0/0/2/1/0/0,Body,24,NAME,1JNL9442633_A-Cable Ladder MVS,A-Cable Ladder MVS
108,None,0/0/2/1/0/0,Body,24,OBJECTTYPE,1JNL9442633_A-Cable Ladder MVS,A-Cable Ladder MVS
109,None,0/0/2/1/0/0,Body,24,Name,1JNL9442633_A-Cable Ladder MVS,A-Cable Ladder MVS
110,None,0/0/2/1/0/0,Body,24,GLOBALID,3D$qDNkUKo_PvZfjcsAJio,PvZfjcsAJio
111,None,0/0/2/1/0/0,Body,24,GLOBALID,2Zu3Gvs34_pPyOHGX_igDX,pPyOHGX_igDX
112,None,0/0/2/1/1/0,Body,43,NAME,1JNL9442631_A-Cable Ladder MVS,A-Cable Ladder MVS
113,None,0/0/2/1/1/0,Body,43,OBJECTTYPE,1JNL9442631_A-Cable Ladder MVS,A-Cable Ladder MVS
114,None,0/0/2/1/1/0,Body,43,Name,1JNL9442631_A-Cable Ladder MVS,A-Cable Ladder MVS
115,None,0/0/2/1/1/0,Body,43,GLOBALID,2LdMGD2$qt7eLQ5uekO9_J,J
116,None,0/0/2/1/1/0,Body,43,GLOBALID,0rdnkbHVa_TPwM3umsW6zP,TPwM3umsW6zP
117,None,0/0/2/1/2/0,Body,48,GLOBALID,398ofjTSKtEQF2DtUiP_MN,MN
118,None,0/0/2/1/2/0,Body,48,NAME,1JNL9441111_A-Cable Ladder 90 450,A-Cable Ladder 90 450
119,None,0/0/2/1/2/0,Body,48,OBJECTTYPE,1JNL9441111_A-Cable Ladder 90 450,A-Cable Ladder 90 450
120,None,0/0/2/1/2/0,Body,48,GLOBALID,3lR7$VA0axQfm_aoAOQaAY,aoAOQaAY
121,None,0/0/2/1/2/0,Body,48,Name,1JNL9441111_A-Cable Ladder 90 450,A-Cable Ladder 90 450
122,None,0/0/2/1/2/0,Body,48,GLOBALID,2A7cFaVcayExGHxefL5_$4,$4
123,None,0/0/2/1/2/0,Body,48,GLOBALID,0$Aq$D1pKrzRdtUJ0G_Epl,Epl
124,None,0/0/2/1/2/0,Body,48,GLOBALID,1tGj5chWOxKgW1PiSbTAG_,
125,None,0/0/2/1/3/0,Body,59,NAME,1JNL9441111_A-Cable Ladder 90 450,A-Cable Ladder 90 450
126,None,0/0/2/1/3/0,Body,59,OBJECTTYPE,1JNL9441111_A-Cable Ladder 90 450,A-Cable Ladder 90 450
127,None,0/0/2/1/3/0,Body,59,Name,1JNL9441111_A-Cable Ladder 90 450,A-Cable Ladder 90 450
128,None,0/0/2/1/3/0,Body,59,GLOBALID,3$UtogwgKu4gYN0_mL9$uF,mL9$uF
129,None,0/0/2/1/3/0,Body,59,GLOBALID,1J2INASauvc8VY1FX_iUbr,iUbr
130,None,0/0/2/1/3/0,Body,59,GLOBALID,2UClV6KoO_GgPmEVkLSFTJ,GgPmEVkLSFTJ
131,None,0/0/2/1/3/0,Body,59,GLOBALID,34yGysOl4olwWtQH_g6hAz,g6hAz
132,None,0/0/2/1/4/0,Body,70,NAME,1JNL9442633_A-Cable Ladder MVS,A-Cable Ladder MVS
133,None,0/0/2/1/4/0,Body,70,OBJECTTYPE,1JNL9442633_A-Cable Ladder MVS,A-Cable Ladder MVS
134,None,0/0/2/1/4/0,Body,70,Name,1JNL9442633_A-Cable Ladder MVS,A-Cable Ladder MVS
135,None,0/0/2/1/4/0,Body,70,GLOBALID,26SWyh6LiuOQRntyfSl_Q$,Q$
136,None,0/0/2/1/4/0,Body,70,GLOBALID,0oQiAROR8qluh28GS_WhJu,WhJu
137,None,0/0/2/1/5/0,Body,89,NAME,1JNL9442631_A-Cable Ladder MVS,A-Cable Ladder MVS
138,None,0/0/2/1/5/0,Body,89,OBJECTTYPE,1JNL9442631_A-Cable Ladder MVS,A-Cable Ladder MVS
139,None,0/0/2/1/5/0,Body,89,Name,1JNL9442631_A-Cable Ladder MVS,A-Cable Ladder MVS
140,None,0/0/2/1/5/0,Body,89,GLOBALID,1uR3VObjqvxeikr_cuoG5y,cuoG5y
141,None,0/0/2/1/6/0,Body,94,NAME,1JNL9442631_A-Cable Ladder MVS,A-Cable Ladder MVS
142,None,0/0/2/1/6/0,Body,94,OBJECTTYPE,1JNL9442631_A-Cable Ladder MVS,A-Cable Ladder MVS
143,None,0/0/2/1/6/0,Body,94,Name,1JNL9442631_A-Cable Ladder MVS,A-Cable Ladder MVS
144,None,0/0/2/1/6/0,Body,94,GLOBALID,0$UPY8qXO_rBZtSVlVPRKs,rBZtSVlVPRKs
145,None,0/0/2/1/6/0,Body,94,GLOBALID,1xctFOB54sae$L_J_Ox266,J_Ox266
146,None,0/0/2/1/7/0,Body,99,NAME,1JNL9441111_A-Cable Ladder 90 450,A-Cable Ladder 90 450
147,None,0/0/2/1/7/0,Body,99,OBJECTTYPE,1JNL9441111_A-Cable Ladder 90 450,A-Cable Ladder 90 450
148,None,0/0/2/1/7/0,Body,99,Name,1JNL9441111_A-Cable Ladder 90 450,A-Cable Ladder 90 450
149,None,0/0/2/1/7/0,Body,99,GLOBALID,28Y4wj5zmxjOGTbaJIsDJ_,
150,None,0/0/2/1/7/0,Body,99,GLOBALID,1tz8yy2vS_9f2vapzE1XTJ,9f2vapzE1XTJ
151,None,0/0/2/1/8/0,Body,110,GLOBALID,2ZUDd04qaouPsj6rCG_lt9,lt9
152,None,0/0/2/1/8/0,Body,110,NAME,1JNL9442633_A-Cable Ladder MVS,A-Cable Ladder MVS
153,None,0/0/2/1/8/0,Body,110,OBJECTTYPE,1JNL9442633_A-Cable Ladder MVS,A-Cable Ladder MVS
154,None,0/0/2/1/8/0,Body,110,Name,1JNL9442633_A-Cable Ladder MVS,A-Cable Ladder MVS
155,None,0/0/2/1/8/0,Body,110,GLOBALID,2TtPDuCHa_bxEg$NQsANXU,bxEg$NQsANXU
156,None,0/0/2/1/8/0,Body,110,GLOBALID,0S4grwB4q_Rhw05f94y4_$,Rhw05f94y4_$
157,None,0/0/2/1/9/0,Body,129,NAME,1JNL9442632_A-Cable Ladder MVS,A-Cable Ladder MVS
158,None,0/0/2/1/9/0,Body,129,OBJECTTYPE,1JNL9442632_A-Cable Ladder MVS,A-Cable Ladder MVS
159,None,0/0/2/1/9/0,Body,129,Name,1JNL9442632_A-Cable Ladder MVS,A-Cable Ladder MVS
160,None,0/0/2/1/9/0,Body,129,GLOBALID,28ZVDhgAWyeA_QutZGGtEu,QutZGGtEu
161,None,0/0/2/1/9/0,Body,129,GLOBALID,0APjO3tzWoUun82Kik_7vQ,7vQ
162,None,0/0/2/1/10/0,Body,147,NAME,1JNL9442632_A-Cable Ladder MVS,A-Cable Ladder MVS
163,None,0/0/2/1/10/0,Body,147,OBJECTTYPE,1JNL9442632_A-Cable Ladder MVS,A-Cable Ladder MVS
164,None,0/0/2/1/10/0,Body,147,GLOBALID,30aesi3Ue_eRIxqVS$RQbu,eRIxqVS$RQbu
165,None,0/0/2/1/10/0,Body,147,Name,1JNL9442632_A-Cable Ladder MVS,A-Cable Ladder MVS
166,None,0/0/2/1/10/0,Body,147,GLOBALID,376WgFefGzNvX2g9apmJ1_,
167,None,0/0/2/1/10/0,Body,147,GLOBALID,14SkNK1T4vpBGnwVVWy_Vc,Vc
168,None,0/0/2/1/11/0,Body,165,GLOBALID,2S2sEEq1Gm4wtZ_39mCcDG,39mCcDG
169,None,0/0/2/1/11/0,Body,165,NAME,1JNL9442632_A-Cable Ladder MVS,A-Cable Ladder MVS
170,None,0/0/2/1/11/0,Body,165,OBJECTTYPE,1JNL9442632_A-Cable Ladder MVS,A-Cable Ladder MVS
171,None,0/0/2/1/11/0,Body,165,GLOBALID,22i6KQzWq_ivVl54MYaexE,ivVl54MYaexE
172,None,0/0/2/1/11/0,Body,165,Name,1JNL9442632_A-Cable Ladder MVS,A-Cable Ladder MVS
173,None,0/0/2/1/11/0,Body,165,GLOBALID,1YYXMGAy4wuRFEeq93i_5O,5O
174,None,0/0/2/1/11/0,Body,165,GLOBALID,1sNiKwqVOvUAsxlQ$fA_RH,RH

Total objects changed: 30
Total property values changed: 175